/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Statuses } from './statuses';
import { AzureVMResponseInstanceViewVmAgentExtensionHandlers } from './azureVMResponseInstanceViewVmAgentExtensionHandlers';


export interface AzureVMResponseInstanceViewVmAgent { 
    extensionHandlers?: Array<AzureVMResponseInstanceViewVmAgentExtensionHandlers>;
    statuses?: Array<Statuses>;
    vmAgentVersion?: string;
}

