/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AzureVMResponseInstanceViewBootDiagnostics } from './azureVMResponseInstanceViewBootDiagnostics';
import { AzureVMResponseInstanceViewDisks } from './azureVMResponseInstanceViewDisks';
import { Statuses } from './statuses';
import { AzureVMResponseInstanceViewMaintenanceRedeployStatus } from './azureVMResponseInstanceViewMaintenanceRedeployStatus';
import { AzureVMResponseInstanceViewVmAgent } from './azureVMResponseInstanceViewVmAgent';
import { AzureVMResponseInstanceViewExtensions } from './azureVMResponseInstanceViewExtensions';


export interface AzureVMResponseInstanceView { 
    bootDiagnostics?: AzureVMResponseInstanceViewBootDiagnostics;
    computerName?: string;
    disks?: Array<AzureVMResponseInstanceViewDisks>;
    extensions?: Array<AzureVMResponseInstanceViewExtensions>;
    hyperVgeneration?: string;
    maintenanceRedeployStatus?: AzureVMResponseInstanceViewMaintenanceRedeployStatus;
    osName?: string;
    osVersion?: string;
    platformFaultDomain?: number;
    platformUpdateDomain?: number;
    rdpThumbPrint?: string;
    statuses?: Array<Statuses>;
    vmAgent?: AzureVMResponseInstanceViewVmAgent;
}

