/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AzureVMResponseInstanceViewMaintenanceRedeployStatus { 
    isCustomerInitiatedMaintenanceAllowed?: boolean;
    lastOperationMessage?: string;
    lastOperationResultCode?: string;
    maintenanceWindowEndTime?: Date;
    maintenanceWindowStartTime?: Date;
    preMaintenanceWindowEndTime?: Date;
    preMaintenanceWindowStartTime?: Date;
}

