/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageResponseBlockDeviceMappings } from './imageResponseBlockDeviceMappings';


export interface ImageResponseImages { 
    architecture?: string;
    blockDeviceMappings?: Array<ImageResponseBlockDeviceMappings>;
    creationDate?: Date;
    description?: string;
    hypervisor?: string;
    imageId?: string;
    imageLocation?: string;
    imageOwnerAlias?: string;
    imageType?: string;
    name?: string;
    ownerId?: string;
    _public?: boolean;
    rootDeviceType?: string;
    state?: string;
    virtualizationType?: string;
}

