/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstanceTypeResponsePricing } from './instanceTypeResponsePricing';


export interface InstanceTypeResponseTypes { 
    ebsIops?: number;
    instanceType?: string;
    memory?: number;
    networkPerformance?: string;
    prettyName?: string;
    pricing?: InstanceTypeResponsePricing;
    vCPU?: number;
}

