/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeyPairResponseFullTags } from './keyPairResponseFullTags';


export interface KeyPairResponseFull { 
    keyFingerprint?: string;
    keyName?: string;
    keyPairId?: string;
    tags?: Array<KeyPairResponseFullTags>;
}

