/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AzureVMResponseInstanceViewDiskEncryptionKeySourceVault } from './azureVMResponseInstanceViewDiskEncryptionKeySourceVault';
import { NetworkResponseAddressSpace } from './networkResponseAddressSpace';


export interface NetworkResponseVirtualNetworkPeerings { 
    allowForwardedTraffic?: boolean;
    allowGatewayTransit?: boolean;
    allowVirtualNetworkAccess?: boolean;
    id?: string;
    name?: string;
    peeringState?: string;
    remoteAddressSpace?: NetworkResponseAddressSpace;
    remoteVirtualNetwork?: AzureVMResponseInstanceViewDiskEncryptionKeySourceVault;
    useRemoteGateways?: boolean;
}

