/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AzureVMResponseInstanceViewDiskEncryptionKeySourceVault } from './azureVMResponseInstanceViewDiskEncryptionKeySourceVault';
import { NetworkResponseTags } from './networkResponseTags';
import { NetworkResponseVirtualNetworkPeerings } from './networkResponseVirtualNetworkPeerings';
import { NetworkResponseDhcpOptions } from './networkResponseDhcpOptions';
import { NetworkResponseBgpCommunities } from './networkResponseBgpCommunities';
import { Subnet } from './subnet';
import { NetworkResponseAddressSpace } from './networkResponseAddressSpace';


export interface NetworkResponse { 
    addressSpace?: NetworkResponseAddressSpace;
    bgpCommunities?: NetworkResponseBgpCommunities;
    ddosProtectionPlan?: AzureVMResponseInstanceViewDiskEncryptionKeySourceVault;
    dhcpOptions?: NetworkResponseDhcpOptions;
    enableDdosProtection?: boolean;
    enableVmProtection?: boolean;
    id?: string;
    location?: string;
    subnets?: Array<Subnet>;
    tags?: NetworkResponseTags;
    virtualNetworkPeerings?: Array<NetworkResponseVirtualNetworkPeerings>;
}

