/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NICResponsePrivateEndpoint } from './nICResponsePrivateEndpoint';
import { AzureVMResponseInstanceViewDiskEncryptionKeySourceVault } from './azureVMResponseInstanceViewDiskEncryptionKeySourceVault';


export interface NICResponse { 
    hostedWorkloads?: Array<string>;
    name?: string;
    privateEndpoint?: NICResponsePrivateEndpoint;
    type?: string;
    virtualMachine?: AzureVMResponseInstanceViewDiskEncryptionKeySourceVault;
}

