/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReservedPricing { 
    yrTerm1ConvertibleAllUpfront?: number;
    yrTerm1ConvertibleNoUpfront?: number;
    yrTerm1ConvertiblePartialUpfront?: number;
    yrTerm1StandardAllUpfront?: number;
    yrTerm1StandardNoUpfront?: number;
    yrTerm1StandardPartialUpfront?: number;
    yrTerm3ConvertibleAllUpfront?: number;
    yrTerm3ConvertibleNoUpfront?: number;
    yrTerm3ConvertiblePartialUpfront?: number;
    yrTerm3StandardAllUpfront?: number;
    yrTerm3StandardNoUpfront?: number;
    yrTerm3StandardPartialUpfront?: number;
}

