/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecurityGroupResponseFullUserIdGroupPairs } from './securityGroupResponseFullUserIdGroupPairs';
import { SecurityGroupResponseFullIpRanges } from './securityGroupResponseFullIpRanges';
import { SecurityGroupResponseFullIpv6Ranges } from './securityGroupResponseFullIpv6Ranges';
import { SecurityGroupResponseFullPrefixListIds } from './securityGroupResponseFullPrefixListIds';


export interface SecurityGroupResponseFullIpPermissions { 
    fromPort?: number;
    ipProtocol?: string;
    ipRanges?: Array<SecurityGroupResponseFullIpRanges>;
    ipv6Ranges?: Array<SecurityGroupResponseFullIpv6Ranges>;
    prefixListIds?: Array<SecurityGroupResponseFullPrefixListIds>;
    toPort?: number;
    userIdGroupPairs?: Array<SecurityGroupResponseFullUserIdGroupPairs>;
}

