/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubnetRouteTable } from './subnetRouteTable';
import { AzureVMResponseInstanceViewDiskEncryptionKeySourceVault } from './azureVMResponseInstanceViewDiskEncryptionKeySourceVault';
import { SubnetNetworkSecurityGroup } from './subnetNetworkSecurityGroup';
import { SubnetServiceEndpoints } from './subnetServiceEndpoints';
import { SubnetServiceEndpointPolicies } from './subnetServiceEndpointPolicies';
import { SubnetDelegations } from './subnetDelegations';


export interface Subnet { 
    addressPrefix?: string;
    addressPrefixes?: Array<string>;
    delegations?: Array<SubnetDelegations>;
    id?: string;
    name?: string;
    natGateway?: AzureVMResponseInstanceViewDiskEncryptionKeySourceVault;
    networkSecurityGroup?: SubnetNetworkSecurityGroup;
    privateEndpointNetworkPolicies?: string;
    privateLinkServiceNetworkPolicies?: string;
    routeTable?: SubnetRouteTable;
    serviceEndpointPolicies?: Array<SubnetServiceEndpointPolicies>;
    serviceEndpoints?: Array<SubnetServiceEndpoints>;
}

