/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubnetNetworkSecurityGroupSourceApplicationSecurityGroups } from './subnetNetworkSecurityGroupSourceApplicationSecurityGroups';


export interface SubnetNetworkSecurityGroupSecurityRules { 
    access?: string;
    description?: string;
    destinationAddressPrefix?: string;
    destinationAddressPrefixes?: Array<string>;
    destinationApplicationSecurityGroups?: Array<string>;
    destinationPortRange?: string;
    destinationPortRanges?: Array<string>;
    direction?: string;
    id?: string;
    name?: string;
    priority?: number;
    protocol?: string;
    sourceAddressPrefix?: string;
    sourceAddressPrefixes?: Array<string>;
    sourceApplicationSecurityGroups?: Array<SubnetNetworkSecurityGroupSourceApplicationSecurityGroups>;
    sourcePortRange?: string;
    sourcePortRanges?: Array<string>;
}

