/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubnetNetworkSecurityGroupSecurityRules } from './subnetNetworkSecurityGroupSecurityRules';
import { NetworkResponseTags } from './networkResponseTags';


export interface SubnetNetworkSecurityGroup { 
    id?: string;
    location?: string;
    securityRules?: Array<SubnetNetworkSecurityGroupSecurityRules>;
    tags?: NetworkResponseTags;
}

