/**
 * Multicloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VMResponseFullGroups } from './vMResponseFullGroups';
import { VMResponseFullPrivateIpAddresses } from './vMResponseFullPrivateIpAddresses';
import { VMResponseFullAssociation } from './vMResponseFullAssociation';
import { VMResponseFullIpv6Addresses } from './vMResponseFullIpv6Addresses';
import { VMResponseFullAttachment } from './vMResponseFullAttachment';


export interface VMResponseFullNetworkInterfaces { 
    association?: VMResponseFullAssociation;
    attachment?: VMResponseFullAttachment;
    description?: string;
    groups?: Array<VMResponseFullGroups>;
    interfaceType?: string;
    ipv6Addresses?: Array<VMResponseFullIpv6Addresses>;
    macAddress?: string;
    networkInterfaceId?: string;
    ownerId?: string;
    privateDnsName?: string;
    privateIpAddress?: string;
    privateIpAddresses?: Array<VMResponseFullPrivateIpAddresses>;
    sourceDestCheck?: boolean;
    status?: string;
    subnetId?: string;
    vpcId?: string;
}

