apiVersion: v1
kind: Service
metadata:
  name:  azure-resource
  namespace: multicloud
  labels:
    app:  azure-resource
spec:
  ports:
  - port: 8080
    name:  azure-resource
    #nodePort: 32000
  type: ClusterIP
  selector:
    app:  azure-resource
