apiVersion: v1
kind: Service
metadata:
  name:  azure-resource
  namespace: multicloud
  labels:
    app:  azure-resource
spec:
  ports:
  - port: 80
    name:  azure-resource
    nodePort: 32001
  type: NodePort
  selector:
    app:  azure-resource
---
apiVersion: v1
kind: Service
metadata:
  name:  azure-image
  namespace: multicloud
  labels:
    app:  azure-image
spec:
  ports:
  - port: 80
    name:  azure-image
    nodePort: 32002
  type: NodePort
  selector:
    app:  azure-image
---
apiVersion: v1
kind: Service
metadata:
  name:  azure-instancetype
  namespace: multicloud
  labels:
    app:  azure-instancetype
spec:
  ports:
  - port: 80
    name:  azure-instancetype
    nodePort: 32003
  type: NodePort
  selector:
    app:  azure-instancetype
