apiVersion: v1
kind: Service
metadata:
  name: multicloud-frontend
  namespace: multicloud
  labels:
    app: multicloud-frontend
spec:
  ports:
  - port: 80
    name: multicloud-frontend
    nodePort: 32500
  type: NodePort
  selector:
    app: multicloud-frontend
