apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
  - image: frontend
    context: frontend
  - image: api
    context: backend/api
  - image: aws-image
    context: backend/aws/aws-image-service
  - image: aws-instancetype
    context: backend/aws/aws-instancetype-service
    jib: {}
  - image: aws-keypair
    context: backend/aws/aws-keypair-service
  - image: aws-securitygroup
    context: backend/aws/aws-securitygroup-service
  - image: aws-vm
    context: backend/aws/aws-vm-service
  - image: aws-vpc
    context: backend/aws/aws-vpc-service
  - image: azure-image
    context: backend/azure/azure-image-service
  - image: azure-instancetype
    context: backend/azure/azure-instancetype-service
  - image: azure-network
    context: backend/azure/azure-network-service
  - image: azure-resource
    context: backend/azure/azure-resource-service
  - image: azure-vm
    context: backend/azure/azure-vm-service
  - image: authentication
    context: authentication
deploy:
  kubectl:
    manifests:
    - ./k8s/deployment*
