apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-frontend #Name of the deployments
  namespace: multicloud
spec:
  replicas: 1 #Number of created pods
  selector:
    matchLabels:
      app: multicloud-frontend
  template:
    metadata:
      labels:
        app: multicloud-frontend #label to set in the pods
    spec:
      containers:
      - name: multicloud-frontend
        image: multicloud-frontend:prod
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "64Mi"
        env:
        - name: AWS_BASE_PATH
          value: "http://localhost:32400/api"
        ports:
        - containerPort: 80 #Expose containerport to the pod
        livenessProbe: #Check that pod is ready
          httpGet:
            path: / #path to check
            port: 80
          initialDelaySeconds: 30 #start checking after 30 seconds
          periodSeconds: 30 #check every 30 seconds
        readinessProbe: #Check that pod is healthy
          httpGet:
            path: / #path to check
            port: 80 #port to check
          initialDelaySeconds: 15 #start checking after 15 seconds
          periodSeconds: 3 #check every 3 seconds
