apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-vm
  namespace: multicloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  aws-vm
  template:
    metadata:
      labels:
        app:  aws-vm
    spec:
      containers:
      - name:  aws-vm
        image: aws-vm:latest
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "64Mi"
        env:
        - name: accessKey
          valueFrom:
            secretKeyRef:
              name: multicloud
              key: awsaccessKey
        - name: secretKey
          valueFrom:
            secretKeyRef:
              name: multicloud
              key: awssecretKey
        ports:
        - containerPort: 80 #Expose containerport to the pod
        livenessProbe: #Check that pod is ready
          httpGet:
            path: / #path to check
            port: 80
          initialDelaySeconds: 30 #start checking after 30 seconds
          periodSeconds: 30 #check every 30 seconds
        readinessProbe: #Check that pod is healthy
          httpGet:
            path: / #path to check
            port: 80 #port to check
          initialDelaySeconds: 15 #start checking after 15 seconds
          periodSeconds: 3 #check every 3 seconds
