apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: multicloud
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    name: frontend
    nodePort: 32500
  type: NodePort
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: multicloud
  labels:
    app: api
spec:
  ports:
  - port: 80
    name: api
    nodePort: 32000
  type: NodePort
  selector:
    app: api
---
apiVersion: v1
kind: Service
metadata:
  name: aws-instancetype
  namespace: multicloud
  labels:
    app: aws-instancetype
spec:
  ports:
  - port: 8080
    name: aws-instancetype
    #nodePort: 32000
  type: ClusterIP
  selector:
    app: aws-instancetype
---
apiVersion: v1
kind: Service
metadata:
  name: aws-securitygroup
  namespace: multicloud
  labels:
    app: aws-securitygroup
spec:
  ports:
  - port: 80
    name: aws-securitygroup
    #nodePort: 32100
  type: ClusterIP
  selector:
    app: aws-securitygroup
---
apiVersion: v1
kind: Service
metadata:
  name: aws-keypair
  namespace: multicloud
  labels:
    app: aws-keypair
spec:
  ports:
  - port: 80
    name: aws-keypair
    #nodePort: 32200
  type: ClusterIP
  selector:
    app: aws-keypair
---
apiVersion: v1
kind: Service
metadata:
  name: aws-image
  namespace: multicloud
  labels:
    app: aws-image
spec:
  ports:
    - port: 80
      name: aws-image
      #nodePort: 32300
  type: ClusterIP
  selector:
    app: aws-image
---
apiVersion: v1
kind: Service
metadata:
  name: aws-vpc
  namespace: multicloud
  labels:
    app: aws-vpc
spec:
  ports:
    - port: 80
      name: aws-image
      #nodePort: 32300
  type: ClusterIP
  selector:
    app: aws-vpc
---
apiVersion: v1
kind: Service
metadata:
  name: aws-vm
  namespace: multicloud
  labels:
    app: aws-vm
spec:
  ports:
  - port: 80
    name: aws-vm
    #nodePort: 32400
  #type: LoadBalancer
  type: ClusterIP
  selector:
    app: aws-vm
---
apiVersion: v1
kind: Service
metadata:
  name:  azure-resource
  namespace: multicloud
  labels:
    app:  azure-resource
spec:
  ports:
  - port: 80
    name:  azure-resource
    #nodePort: 32001
  type: ClusterIP
  selector:
    app:  azure-resource
---
apiVersion: v1
kind: Service
metadata:
  name:  azure-image
  namespace: multicloud
  labels:
    app:  azure-image
spec:
  ports:
  - port: 80
    name:  azure-image
    #nodePort: 32002
  type: ClusterIP
  selector:
    app:  azure-image
---
apiVersion: v1
kind: Service
metadata:
  name:  azure-instancetype
  namespace: multicloud
  labels:
    app:  azure-instancetype
spec:
  ports:
  - port: 80
    name:  azure-instancetype
    #nodePort: 32003
  type: ClusterIP
  selector:
    app:  azure-instancetype
---
apiVersion: v1
kind: Service
metadata:
  name:  azure-network
  namespace: multicloud
  labels:
    app:  azure-network
spec:
  ports:
  - port: 80
    name:  azure-network
    #nodePort: 32004
  type: ClusterIP
  selector:
    app:  azure-network
---
apiVersion: v1
kind: Service
metadata:
  name:  azure-vm
  namespace: multicloud
  labels:
    app:  azure-vm
spec:
  ports:
  - port: 80
    name:  azure-vm
    #nodePort: 32005
  type: ClusterIP
  selector:
    app:  azure-vm
---
apiVersion: v1
kind: Service
metadata:
  name:  authentication
  namespace: multicloud
  labels:
    app:  authentication
spec:
  ports:
  - port: 8080
    name:  authentication
    #nodePort: 32300
  type: ClusterIP
  selector:
    app:  authentication
