apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend #Name of the deployments
spec:
  replicas: 1 #Number of created pods
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend #label to set in the pods
    spec:
      containers:
      - name: frontend
        image: frontend:prod
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
        ports:
        - containerPort: 80 #Expose containerport to the pod
        livenessProbe: #Check that pod is ready
          httpGet:
            path: / #path to check
            port: 80
          initialDelaySeconds: 30 #start checking after 30 seconds
          periodSeconds: 30 #check every 30 seconds
        readinessProbe: #Check that pod is healthy
          httpGet:
            path: / #path to check
            port: 80 #port to check
          initialDelaySeconds: 15 #start checking after 15 seconds
          periodSeconds: 3 #check every 3 seconds
