apiVersion: v1
kind: Service
metadata:
  name: aws-instancetype
  namespace: multicloud
  labels:
    app: aws-instancetype
spec:
  ports:
  - port: 8080
    name: aws-instancetype
    #nodePort: 32000
  type: ClusterIP
  selector:
    app: aws-instancetype
---
apiVersion: v1
kind: Service
metadata:
  name: aws-securitygroup
  namespace: multicloud
  labels:
    app: aws-securitygroup
spec:
  ports:
  - port: 80
    name: aws-securitygroup
    #nodePort: 32100
  type: ClusterIP
  selector:
    app: aws-securitygroup
---
apiVersion: v1
kind: Service
metadata:
  name: aws-keypair
  namespace: multicloud
  labels:
    app: aws-keypair
spec:
  ports:
  - port: 80
    name: aws-keypair
    #nodePort: 32200
  type: ClusterIP
  selector:
    app: aws-keypair
---
apiVersion: v1
kind: Service
metadata:
  name: aws-image
  namespace: multicloud
  labels:
    app: aws-image
spec:
  ports:
    - port: 80
      name: aws-image
      #nodePort: 32300
  type: ClusterIP
  selector:
    app: aws-image
---
apiVersion: v1
kind: Service
metadata:
  name: aws-vpc
  namespace: multicloud
  labels:
    app: aws-vpc
spec:
  ports:
    - port: 80
      name: aws-image
      #nodePort: 32300
  type: ClusterIP
  selector:
    app: aws-vpc
---
apiVersion: v1
kind: Service
metadata:
  name: aws-vm
  namespace: multicloud
  labels:
    app: aws-vm
spec:
  ports:
  - port: 80
    name: aws-vm
    nodePort: 32400
  #type: LoadBalancer
  type: NodePort
  selector:
    app: aws-vm
