/**
 * Swagger REST Article
 * This is the swagger file that goes with our server code
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InstanceTypeResponseTypes { 
    ebsIops?: number;
    instanceType?: string;
    memory?: number;
    networkPerformance?: string;
    prettyName?: string;
    vCPU?: number;
}

