/**
 * Swagger REST Article
 * This is the swagger file that goes with our server code
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VMResponseFullInstances } from './vMResponseFullInstances';
import { VMResponseFullGroups } from './vMResponseFullGroups';


export interface VMResponseFull { 
    groups?: Array<VMResponseFullGroups>;
    instances?: Array<VMResponseFullInstances>;
    ownerId?: string;
    requesterId?: string;
    reservationId?: string;
}

