/**
 * Swagger REST Article
 * This is the swagger file that goes with our server code
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VPCListResponseCidrBlockState } from './vPCListResponseCidrBlockState';


export interface VPCListResponseIpv6CidrBlockAssociationSet { 
    associationId?: string;
    ipv6CidrBlock?: string;
    ipv6CidrBlockState?: VPCListResponseCidrBlockState;
    ipv6Pool?: string;
    networkBorderGroup?: string;
}

