/**
 * Swagger REST Article
 * This is the swagger file that goes with our server code
 *
 * The version of the OpenAPI document: 1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VPCListResponseIpv6CidrBlockAssociationSet } from './vPCListResponseIpv6CidrBlockAssociationSet';
import { VPCListResponseCidrBlockAssociationSet } from './vPCListResponseCidrBlockAssociationSet';
import { VPCListResponseTags } from './vPCListResponseTags';


export interface VPCListResponseVps { 
    cidrBlock?: string;
    cidrBlockAssociationSet?: Array<VPCListResponseCidrBlockAssociationSet>;
    dhcpOptionsId?: string;
    instanceTenancy?: string;
    ipv6CidrBlockAssociationSet?: Array<VPCListResponseIpv6CidrBlockAssociationSet>;
    isDefault?: boolean;
    ownerId?: string;
    state?: string;
    tags?: Array<VPCListResponseTags>;
    vpcId?: string;
}

