export * from './createVM.service';
import { CreateVMService } from './createVM.service';
export * from './getVM.service';
import { GetVMService } from './getVM.service';
export * from './image.service';
import { ImageService } from './image.service';
export * from './instancetype.service';
import { InstancetypeService } from './instancetype.service';
export * from './keypair.service';
import { KeypairService } from './keypair.service';
export * from './securitygroup.service';
import { SecuritygroupService } from './securitygroup.service';
export * from './startVM.service';
import { StartVMService } from './startVM.service';
export * from './stopVM.service';
import { StopVMService } from './stopVM.service';
export * from './vpc.service';
import { VpcService } from './vpc.service';
export const APIS = [CreateVMService, GetVMService, ImageService, InstancetypeService, KeypairService, SecuritygroupService, StartVMService, StopVMService, VpcService];
