export * from './aWSImage.service';
import { AWSImageService } from './aWSImage.service';
export * from './aWSInstancetype.service';
import { AWSInstancetypeService } from './aWSInstancetype.service';
export * from './aWSKeypair.service';
import { AWSKeypairService } from './aWSKeypair.service';
export * from './aWSSecuritygroup.service';
import { AWSSecuritygroupService } from './aWSSecuritygroup.service';
export * from './aWSVm.service';
import { AWSVmService } from './aWSVm.service';
export * from './aWSVpc.service';
import { AWSVpcService } from './aWSVpc.service';
export * from './aZUREImage.service';
import { AZUREImageService } from './aZUREImage.service';
export * from './aZUREInstancetypes.service';
import { AZUREInstancetypesService } from './aZUREInstancetypes.service';
export * from './aZURENetwork.service';
import { AZURENetworkService } from './aZURENetwork.service';
export * from './aZUREResourcegroup.service';
import { AZUREResourcegroupService } from './aZUREResourcegroup.service';
export * from './aZUREVm.service';
import { AZUREVmService } from './aZUREVm.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export const APIS = [AWSImageService, AWSInstancetypeService, AWSKeypairService, AWSSecuritygroupService, AWSVmService, AWSVpcService, AZUREImageService, AZUREInstancetypesService, AZURENetworkService, AZUREResourcegroupService, AZUREVmService, AuthenticationService];
