apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: azure-resource-service
build:
  artifacts:
  - image: azure-resource
deploy:
  kubectl:
    manifests:
    - ../../../k8s/deployment_azure-resource.yaml
