apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: multicloud
  labels:
    app: api
spec:
  ports:
  - port: 80
    name: api
    nodePort: 32000
  type: NodePort
  selector:
    app: api
