apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: authentication
build:
  artifacts:
  - image: authentication
deploy:
  kubectl:
    manifests:
    - ../k8s/deployment_authentication.yaml
